# -*- coding: utf-8 -*-
"""Dane pięciu projektów MoVilla (z katalogów PDF). Importowane przez build_site.py."""

# ---------------------------------------------------------------- data
STD_ARC = [
    ("Fundament", "płyta fundamentowa"),
    ("Konstrukcja", "stalowa konstrukcja szkieletowa"),
    ("Dach", "konstrukcja, izolacja, blacha na rąbek"),
    ("Ściany zewnętrzne", "warstwy zgodnie z przekrojem DSZ / SZ"),
    ("Ścianki działowe", "zgodnie z projektem"),
    ("Instalacja wod‑kan", "rozprowadzenie instalacji"),
    ("Instalacja elektryczna", "rozprowadzenie instalacji"),
    ("Ogrzewanie", "podłogowe, maty grzewcze"),
    ("Stolarka", "okna, drzwi zewnętrzne, drzwi tarasowe"),
    ("Wnętrze", "przygotowane do prac wykończeniowych"),
]
STD_BARN = STD_ARC[:4] + [("Fasada i ściany szczytowe", "elewacja, ocieplenie"), ("Schody na antresolę", "w zakresie")] + STD_ARC[4:]
STD_FOREST = [
    ("Konstrukcja stalowa", "ocynkowana rama + łączniki"),
    ("Ściany zewnętrzne i wewnętrzne", "system warstwowych przegród"),
    ("Stolarka", "okna i drzwi aluminiowe"),
    ("Warstwy podłogowe", "z wykończeniem SPC lub drewnianym"),
    ("Instalacja wod‑kan", "podstawowa, rury PPR / PVC"),
    ("Instalacja elektryczna", "oprawy, gniazda, rozdzielnica"),
    ("Wyposażenie łazienek", "umywalka, lustro, prysznic, WC, armatura"),
    ("Wykończenie wnętrza", "panele dekoracyjne, płytki w łazienkach"),
    ("Taras użytkowy", "na drugiej kondygnacji"),
    ("Dokumentacja techniczna", "przygotowanie pod realizację"),
]
SPEC_ARC = [
    ("DSZ1 · Dach / ściana główna", "U ≤ 0,15 W/m²K", "425 mm",
     "Główna przegroda domu: łukowa (ArcHouse, MYSA) lub dwuspadowa (BarnHouse). Warstwy od zewnątrz.",
     [("Blacha na rąbek stojący", ""), ("Ekran włóknisty paroprzepuszczalny", ""), ("Pełne deskowanie z płyty OSB", "20 mm"),
      ("Szczelina wentylacyjna, listwy 40×40", "40 mm"), ("Membrana wstępnego krycia", ""), ("Wełna mineralna między łatami", "80 mm"),
      ("Wełna mineralna między krokwiami stalowymi IPE 180", "180 mm"), ("Ruszt stalowy wypełniony wełną", "80 mm"),
      ("Paroizolacja aktywna", ""), ("Płyta GK 2 × 12,5", "25 mm")]),
    ("DSZ2 · Dach wiatrołapu", "U ≤ 0,15 W/m²K", "335–370 mm", "",
     [("Blacha na rąbek stojący", ""), ("Ekran włóknisty paroprzepuszczalny", ""), ("Pełne deskowanie z płyty OSB", "20 mm"),
      ("Szczelina wentylacyjna, listwy 40×40", "40 mm"), ("Membrana wstępnego krycia", ""), ("Wełna mineralna między łatami", "90–130 mm"),
      ("Wełna mineralna między krokwiami stalowymi", "160 mm"), ("Paroizolacja aktywna", ""), ("Płyta GK 2 × 12,5", "25 mm")]),
    ("SZ1 · Ściana szczytowa", "U ≤ 0,20 W/m²K", "365 mm", "Przeszklona lub pełna ściana szczytowa z drewnianą elewacją.",
     [("Deski elewacyjne", "20 mm"), ("Łaty, szczelina wentylacyjna 40×40", "40 mm"), ("Płyta drzewna otwarta dyfuzyjnie", "20 mm"),
      ("Konstrukcja stalowa 90 + kontrłaty 80, wełna mineralna", "170 mm"), ("Profile stalowe 90, wełna mineralna", "90 mm"),
      ("Paroizolacja aktywna", ""), ("Płyta GK 2 × 12,5", "25 mm")]),
    ("SZ2 · Ściana wiatrołapu", "U ≤ 0,20 W/m²K", "325 mm", "",
     [("Panele lub deski elewacyjne", "20 mm"), ("Łaty, szczelina wentylacyjna 40×40", "40 mm"), ("Płyta drzewna otwarta dyfuzyjnie", "20 mm"),
      ("Kontrłaty drewniane 60, wełna mineralna", "60 mm"), ("Łaty drewniane 80, wełna mineralna", "80 mm"),
      ("Konstrukcja stalowa 80, wełna mineralna", "80 mm"), ("Paroizolacja aktywna", ""), ("Płyta GK 2 × 12,5", "25 mm")]),
    ("PP · Podłoga parteru", "U ≤ 0,30 W/m²K", "", "Warstwa wykończeniowa (parkiet, terakota) po stronie inwestora, o ile oferta nie stanowi inaczej.",
     [("Warstwa wykończeniowa inwestora", "ok. 20 mm"), ("Wylewka cementowa, jastrych", "60 mm"), ("Ogrzewanie podłogowe", ""),
      ("Folia izolacyjna", ""), ("Styropian podłogowy EPS", "120 mm"), ("Izolacja przeciwwilgociowa, folia budowlana", ""),
      ("Płyta fundamentowa wg projektu", "250 mm"), ("2 × folia budowlana na zakład", ""), ("Styrodur 4000 CS", "200 mm"),
      ("Chudy beton B10", "100 mm"), ("Podbudowa: tłuczeń, pospółka", "300–400 mm")]),
    ("Stolarka i szklenie", "Uw od 0,5 W/m²K", "", "Fasada słupowo‑ryglowa RAL 7016 w systemie MC WALL ALIPLAST, okna GENESIS ALIPLAST. Szklenie potrójne; grubość i typ szkła dobierane do strefy wiatrowej (powłoki Antisol, Cool Light, Sun Guard). Statyka wg PN‑EN 1991‑1‑3 i 1991‑1‑4.", []),
]
SPEC_FOREST = [
    ("Konstrukcja", "rama stalowa", "ocynk", "Lekka rama stalowa z ocynkowanych profili zamkniętych z kompletem łączników, kątowników i śrub kotwiących.",
     [("Profile 140 × 80 mm", "słupy, rygle"), ("Profile 80 × 80 mm", ""), ("Profile 40 × 60 i 40 × 80 mm", ""), ("Łączniki, kątowniki, śruby kotwiące", "")]),
    ("Ściany zewnętrzne", "system prefabrykowany", "155 mm", "",
     [("Panel izolacyjny ze stopu cynku i aluminium", "16 mm"), ("Płyta XPS", "50 mm"), ("Płyta OSB", "9 mm"), ("Izolacja ścienna", "80 mm")]),
    ("Ściany wewnętrzne i łazienki", "", "47 mm", "",
     [("Płyta OSB", "9 mm"), ("Izolacja XPS", "30 mm"), ("Panel dekoracyjny", "8 mm"), ("Łazienki: płyty kompozytowe odporne na wilgoć", "")]),
    ("Podłoga", "", "", "",
     [("Płyta cementowo‑włóknowa", "18 mm"), ("Podłoga SPC 6 mm lub drewniana 12 mm", ""), ("Folia przeciwwilgociowa", "0,3–0,5 mm"), ("Łazienka: płytki antypoślizgowe", "9 mm")]),
    ("Stolarka", "aluminium, argon, Low‑E", "", "",
     [("Drzwi wejściowe: aluminiowe, przesuwne, szklane", "1600 × 2100 mm"), ("Drzwi łazienkowe: szkło prywatności", "700 × 2050 mm"), ("Okna: profile aluminiowe z przekładką termiczną, szyby z argonem i powłoką Low‑E", "")]),
    ("Instalacje i wyposażenie", "w standardzie", "", "",
     [("Instalacja wodna z rur PPR", ""), ("Kanalizacja PVC", "110 / 50 mm"), ("Instalacja elektryczna: oprawy downlight, przełączniki, gniazda, rozdzielnica", ""), ("Łazienki: umywalka, lustro, zestaw prysznicowy, toaleta, armatura", "")]),
]

def VAR_ARC(pre, full):
    return [
        ("Antresola otwarta", "Otwarta antresola połączona wizualnie z salonem: lekkość, optyczne powiększenie i lepsze doświetlenie. Sypialnia, gabinet lub strefa relaksu.", "w standardzie", f"{pre}/plan-open.webp", "Rzut parteru i antresoli otwartej"),
        ("Pełny strop + balkon", f"Pełnowymiarowe piętro jako prywatna strefa z sypialniami, garderobą, łazienką lub gabinetem. Opcja z balkonem lub bez.{full}", "opcja", None, "Rzut piętra, pełny strop"),
        ("Antresola zamknięta", "Wydzielona przestrzeń na piętrze, więcej prywatności i komfortu. Sypialnia, gabinet, pokój dziecięcy.", "opcja", None, "Rzut antresoli zamkniętej"),
        ("Garaż lub garaż z tarasem", "Do każdego modelu można dodać garaż albo garaż z tarasem na dachu.", "opcja dodatkowa", f"{pre}/garage.webp", "Wizualizacja z garażem"),
    ]

PROJECTS = [
    dict(slug="archouse-70", name="ArcHouse", num="70", family="Łukowy dach", family_key="arc", area=69.5,
        tagline="Kompaktowy dom całoroczny o łukowej bryle. Parter z antresolą, przeszklony szczyt, standard deweloperski podwyższony.",
        card_desc="Łuk, antresola i przeszklony szczyt. Start dla pary lub małej rodziny.", hero="arc70/hero.webp",
        dims="7,28 × 7,60 m", layout="parter + antresola", height="6,9 m", people="",
        params=[("69,50", "m²", "powierzchnia razem"), ("7,28 × 7,60", "m", "wymiary w osiach"), ("6,9", "m", "wysokość kalenicy"), ("30–60", "dni", "czas realizacji")],
        intro_title="Łuk, który otwiera przestrzeń.",
        intro=["ArcHouse 70 to całoroczny dom w technologii stalowej konstrukcji szkieletowej, zaprojektowany w charakterystycznej formie łukowego dachu. Bryła oparta na rzucie prostokąta, z przylegającym wiatrołapem w połowie ściany podłużnej.",
               "Parter mieści otwartą strefę dzienną z kuchnią, łazienkę i wiatrołap. Antresola, przewidziana na około 2/3 długości budynku, to sypialnia, gabinet albo strefa relaksu, w wersji otwartej lub zamkniętej.",
               "Propozycja dla osób, które szukają komfortowego, nowoczesnego domu w atrakcyjnej cenie: solidnie wykonanego i gotowego do wykończenia według własnych potrzeb."],
        facts=[("Powierzchnia parteru", "54,12 m²"), ("Powierzchnia antresoli", "15,38 m²"), ("Wysokość w kalenicy", "ok. 6,9 m"), ("Poziom parteru", "+40 cm nad terenem"), ("Podpiwniczenie", "brak"), ("Posadowienie", "płyta fundamentowa")],
        gallery=[("arc70/ext-2.webp", "Elewacja frontowa"), ("arc70/vertical.webp", "Przeszklony szczyt o zmierzchu"), ("arc70/ext-4.webp", "Bryła w zabudowie"), ("arc70/lake-1.webp", "Nad wodą"), ("arc70/lake-2.webp", "Strefa wejściowa i taras")],
        stats=[("Powierzchnia razem", "69.5", 1, "m²", "parter i antresola"), ("Parter", "54.12", 2, "m²", "strefa dzienna, kuchnia, łazienka, wiatrołap"), ("Antresola", "15.38", 2, "m²", "na ok. 2/3 długości budynku"),
               ("Wysokość", "6.9", 1, "m", "od terenu do kalenicy"), ("U dachu i ścian", "0.15", 2, "W/m²K", "główne przegrody zewnętrzne"), ("Realizacja", "60", 0, "dni", "orientacyjnie 30–60 dni")],
        interiors=[("arc70/int-1.webp", False), ("arc70/int-3.webp", False), ("arc70/int-2.webp", False), ("arc70/int-4.webp", False)],
        variants=VAR_ARC("../img/arc70", " Wariant ok. 80 m²."),
        plans=[("arc70/plan-open.webp", "Antresola otwarta", "rzut parteru + antresoli"), ("arc70/plan-full.webp", "Pełny strop + balkon", "rzut piętra, wariant ok. 80 m²"), ("arc70/section.webp", "Przekrój", "wysokości i poziomy")],
        spec=SPEC_ARC, standard=STD_ARC, next="mysa-120"),
    dict(slug="mysa-120", name="MYSA", num="120", family="Łukowy dach", family_key="arc", area=120.2,
        tagline="Większy z domów łukowych: przestronny parter, pełne piętro lub antresola i ponad 120 m² dla całej rodziny.",
        card_desc="Wydłużony łuk: 90 m² parteru i pełnowymiarowe piętro.", hero="mysa120/hero.webp",
        dims="7,28 × 12,90 m", layout="parter + piętro", height="6,9 m", people="",
        params=[("120,20", "m²", "powierzchnia razem"), ("7,28 × 12,90", "m", "wymiary w osiach"), ("6,9", "m", "wysokość kalenicy"), ("30–60", "dni", "czas realizacji")],
        intro_title="Więcej domu pod tym samym łukiem.",
        intro=["MYSA 120 to wydłużona wersja domu łukowego: 90 m² parteru i blisko 30 m² piętra. Ta sama technologia krążyn stalowych, ta sama forma, ale przestrzeń dla rodziny, która potrzebuje kilku sypialni i osobnej strefy nocnej.",
               "Parter to duża strefa dzienna z kuchnią i jadalnią, sypialnia, łazienka oraz wiatrołap. Piętro można zrealizować jako otwartą lub zamkniętą antresolę albo pełny strop z balkonem.",
               "Dom całoroczny w standardzie deweloperskim podwyższonym, przekazywany z instalacjami, stolarką i ogrzewaniem podłogowym."],
        facts=[("Powierzchnia parteru", "90,33 m²"), ("Powierzchnia piętra", "29,87 m²"), ("Wysokość w kalenicy", "ok. 6,9 m"), ("Poziom parteru", "+40 cm nad terenem"), ("Podpiwniczenie", "brak"), ("Posadowienie", "płyta fundamentowa")],
        gallery=[("mysa120/ext-2.webp", "Elewacja frontowa"), ("mysa120/vertical.webp", "Szczyt o zmierzchu"), ("mysa120/balcony-1.webp", "Wariant z balkonem"), ("mysa120/family.webp", "Dom dla rodziny"), ("mysa120/lake-4.webp", "Nad wodą")],
        stats=[("Powierzchnia razem", "120.2", 1, "m²", "parter i piętro"), ("Parter", "90.33", 2, "m²", "strefa dzienna, sypialnia, łazienka, wiatrołap"), ("Piętro", "29.87", 2, "m²", "antresola lub pełny strop"),
               ("Wysokość", "6.9", 1, "m", "od terenu do kalenicy"), ("U dachu i ścian", "0.15", 2, "W/m²K", "główne przegrody zewnętrzne"), ("Realizacja", "60", 0, "dni", "orientacyjnie 30–60 dni")],
        interiors=[("mysa120/int-1.webp", False), ("mysa120/int-3.webp", False), ("mysa120/int-2.webp", False), ("mysa120/int-4.webp", False), ("mysa120/int-5.webp", False)],
        variants=[("Antresola otwarta", "Otwarta antresola połączona wizualnie z salonem: lekkość, optyczne powiększenie i lepsze doświetlenie.", "w standardzie", "../img/mysa120/plan-open.webp", "Rzut parteru i antresoli"),
                  ("Pełny strop + balkon", "Pełnowymiarowe piętro jako prywatna strefa z sypialniami, garderobą, łazienką lub gabinetem. Opcja z balkonem lub bez.", "opcja", "../img/mysa120/balcony-2.webp", "Wizualizacja z balkonem"),
                  ("Antresola zamknięta", "Wydzielona przestrzeń na piętrze: więcej prywatności i komfortu.", "opcja", None, "Rzut antresoli zamkniętej"),
                  ("Garaż lub garaż z tarasem", "Do każdego modelu można dodać garaż lub garaż z tarasem na dachu.", "opcja dodatkowa", "../img/mysa120/garage-terrace.webp", "Wizualizacja z garażem i tarasem")],
        plans=[("mysa120/plan-open.webp", "Rzut parteru i antresoli", "wariant z antresolą otwartą"), ("mysa120/section.webp", "Przekrój", "wysokości i poziomy, bryła łukowa")],
        spec=SPEC_ARC, standard=STD_ARC, next="barnhouse-85"),
    dict(slug="barnhouse-85", name="BarnHouse", num="85", family="Nowoczesna stodoła", family_key="barn", area=85,
        tagline="Klasyczna forma współczesnej stodoły w technologii stalowej. 85 m² z antresolą, przeszklonym szczytem i dachem z blachy na rąbek.",
        card_desc="Współczesna stodoła w stali. Zwarta, z antresolą.", hero="barn85/hero.webp",
        dims="7,28 × 7,60 m", layout="parter + antresola", height="7,9 m", people="",
        params=[("85", "m²", "powierzchnia razem"), ("7,28 × 7,60", "m", "wymiary w osiach"), ("7,9", "m", "wysokość kalenicy"), ("30–60", "dni", "czas realizacji")],
        intro_title="Stodoła, którą znasz. Nowa technologia.",
        intro=["BarnHouse łączy technologię MoVilla z klasyczną formą inspirowaną współczesną stodołą. Dwuspadowy dach, przeszklona ściana szczytowa i prosta, elegancka bryła na rzucie prostokąta.",
               "Parter mieści otwartą strefę dzienną z kuchnią, łazienkę oraz wiatrołap przylegający do ściany podłużnej. Antresola, na około 2/3 długości budynku, pełni rolę sypialni lub gabinetu. Schody na antresolę są w standardzie.",
               "Budynek opracowano na sprawdzonych parametrach modelu MoVilla BarnHouse, z gwarancją solidności wszystkich zastosowanych elementów."],
        facts=[("Powierzchnia", "85 m²"), ("Układ", "parter + antresola"), ("Wysokość w kalenicy", "ok. 7,9 m"), ("Poziom parteru", "+40 cm nad terenem"), ("Podpiwniczenie", "brak"), ("Posadowienie", "płyta fundamentowa")],
        gallery=[("barn85/ext-2.webp", "Elewacja z tarasem"), ("barn130/vertical.webp", "Wieczorem"), ("barn85/ext-3.webp", "Widok boczny"), ("barn85/aerial.webp", "Bryła w otoczeniu"), ("barn130/night.webp", "Nocą")],
        stats=[("Powierzchnia razem", "85", 0, "m²", "parter i antresola"), ("Szerokość", "7.28", 2, "m", "w osiach konstrukcyjnych"), ("Długość", "7.6", 1, "m", "w osiach konstrukcyjnych"),
               ("Wysokość", "7.9", 1, "m", "od terenu do kalenicy"), ("U dachu i ścian", "0.15", 2, "W/m²K", "główne przegrody zewnętrzne"), ("Realizacja", "60", 0, "dni", "orientacyjnie 30–60 dni")],
        interiors=[("barn85/int-1.webp", False), ("barn85/int-2.webp", False), ("arc70/int-3.webp", False), ("mysa120/int-5.webp", False)],
        variants=[("Antresola", "Sypialnia lub gabinet nad strefą dzienną, otwarta na salon lub wydzielona ścianką.", "w standardzie", "../img/barn85/plan-antresola.webp", "Rzut antresoli"),
                  ("BarnHouse 130", "Ta sama forma w większym metrażu: 130 m² z pełnowymiarowym piętrem.", "większy model", "../img/barn130/hero.webp", "BarnHouse 130"),
                  ("Garaż lub garaż z tarasem", "Do każdego modelu można dodać garaż albo garaż z tarasem na dachu.", "opcja dodatkowa", None, "Opcja dodatkowa")],
        plans=[("barn85/plan-parter.webp", "Rzut parteru", "strefa dzienna, kuchnia, łazienka, wiatrołap"), ("barn85/plan-antresola.webp", "Rzut antresoli", "sypialnia lub gabinet"), ("barn85/section.webp", "Przekrój", "wysokości i poziomy")],
        spec=SPEC_ARC, standard=STD_BARN, next="barnhouse-130"),
    dict(slug="barnhouse-130", name="BarnHouse", num="130", family="Nowoczesna stodoła", family_key="barn", area=130,
        tagline="Największy dom w ofercie: 130 m² w formie współczesnej stodoły. Pełna strefa dzienna na parterze i prywatna część nocna na piętrze.",
        card_desc="130 m² dla dużej rodziny. Pełne piętro, przeszklony szczyt.", hero="barn130/hero.webp",
        dims="szer. 7,28 m", layout="parter + piętro", height="7,9 m", people="",
        params=[("130", "m²", "powierzchnia razem"), ("7,28", "m", "szerokość w osiach"), ("7,9", "m", "wysokość kalenicy"), ("30–60", "dni", "czas realizacji")],
        intro_title="Dom dla całej rodziny. Bez kompromisów.",
        intro=["BarnHouse 130 to rozwinięcie modelu 85: wydłużona bryła współczesnej stodoły, która daje pełną strefę dzienną na parterze i wydzieloną część nocną na piętrze.",
               "Parter: przestronny salon z kuchnią i jadalnią, sypialnia lub gabinet, łazienka, wiatrołap i pomieszczenie gospodarcze. Piętro: sypialnie z łazienką i miejsce na garderobę.",
               "Dom całoroczny w stalowej konstrukcji szkieletowej, przekazywany w standardzie deweloperskim podwyższonym: z fasadą, ociepleniem, instalacjami, schodami i ogrzewaniem podłogowym."],
        facts=[("Powierzchnia", "130 m²"), ("Układ", "parter + piętro"), ("Wysokość w kalenicy", "ok. 7,9 m"), ("Poziom parteru", "+40 cm nad terenem"), ("Podpiwniczenie", "brak"), ("Posadowienie", "płyta fundamentowa")],
        gallery=[("barn130/night.webp", "Wieczorne oświetlenie"), ("barn130/vertical.webp", "Nad jeziorem"), ("barn130/ext-2.webp", "Elewacja boczna"), ("barn130/aerial.webp", "Z lotu ptaka"), ("barn85/ext-2.webp", "Taras i przeszklenia")],
        stats=[("Powierzchnia razem", "130", 0, "m²", "parter i piętro"), ("Szerokość", "7.28", 2, "m", "w osiach konstrukcyjnych"), ("Kondygnacje", "2", 0, "", "parter + pełne piętro"),
               ("Wysokość", "7.9", 1, "m", "od terenu do kalenicy"), ("U dachu i ścian", "0.15", 2, "W/m²K", "główne przegrody zewnętrzne"), ("Realizacja", "60", 0, "dni", "orientacyjnie 30–60 dni")],
        interiors=[("barn130/int-2.webp", False), ("barn130/int-1.webp", False), ("mysa120/int-3.webp", False), ("mysa120/int-4.webp", False)],
        variants=[("Pełne piętro", "Piętro jako prywatna strefa nocna: sypialnie, łazienka, garderoba. Schody w standardzie.", "w standardzie", "../img/barn130/plan-antresola.webp", "Rzut piętra"),
                  ("BarnHouse 85", "Ta sama forma w kompaktowym metrażu: 85 m² z antresolą.", "mniejszy model", "../img/barn85/hero.webp", "BarnHouse 85"),
                  ("Garaż lub garaż z tarasem", "Do każdego modelu można dodać garaż albo garaż z tarasem na dachu.", "opcja dodatkowa", None, "Opcja dodatkowa")],
        plans=[("barn130/plan-parter.webp", "Rzut parteru", "salon, kuchnia, sypialnia, łazienka, wiatrołap"), ("barn130/plan-antresola.webp", "Rzut piętra", "sypialnie, łazienka"), ("barn130/section.webp", "Przekrój", "wysokości i poziomy")],
        spec=SPEC_ARC, standard=STD_BARN, next="foresthouse"),
    dict(slug="foresthouse", name="ForestHouse", num="", family="A‑frame", family_key="forest", area=90,
        tagline="Kompaktowy dom A‑frame na 4 osoby: całoroczny, rekreacyjny albo inwestycyjny. W standardzie z wykończeniem wnętrza i wyposażeniem łazienek.",
        card_desc="A‑frame z tarasem. Gotowy produkt pod wynajem lub glamping.", hero="forest/hero.webp",
        dims="8,30 × 8,00 m", layout="2 sypialnie · 2 łazienki", height="7,0 m", people="4 osoby",
        params=[("90", "m²", "powierzchnia budynku"), ("8,30 × 8,00", "m", "wymiary zewnętrzne"), ("7,0", "m", "wysokość"), ("4", "osoby", "układ dla")],
        intro_title="Bliżej natury. Gotowy do zamieszkania.",
        intro=["ForestHouse to kompaktowy dom w stylistyce A‑frame, zaprojektowany z myślą o nowoczesnym wypoczynku, inwestycjach pod wynajem i całorocznym użytkowaniu. Trójkątna bryła, wysokie przeszklenia frontowe i taras łączą komfort domu z bliskością natury.",
               "Parter to otwarta strefa dzienna z salonem, kuchnią, łazienką i sypialnią. Na drugiej kondygnacji jest prywatna część z sypialnią pod połacią dachu, łazienką i wyjściem na taras.",
               "W odróżnieniu od pozostałych modeli ForestHouse przekazujemy jako kompletne rozwiązanie: z wykończeniem wnętrza, panelami dekoracyjnymi i podstawowym wyposażeniem sanitarnym łazienek."],
        facts=[("Powierzchnia", "90 m²"), ("Wymiary zewnętrzne", "8,30 × 8,00 m"), ("Wysokość", "ok. 7,00 m"), ("Sypialnie", "2"), ("Łazienki", "2"), ("Technologia", "stal + ściany prefabrykowane")],
        gallery=[("forest/ext-2.webp", "W lesie"), ("forest/vertical.webp", "Osiedle A‑frame"), ("forest/ext-3.webp", "Na słupach, nad wodą"), ("forest/glamping.webp", "Zespół pięciu domów"), ("forest/ext-4.webp", "Przeszklony front")],
        stats=[("Powierzchnia", "90", 0, "m²", "powierzchnia budynku"), ("Szerokość", "8.3", 1, "m", "wymiar zewnętrzny"), ("Głębokość", "8", 1, "m", "wymiar zewnętrzny"),
               ("Wysokość", "7", 1, "m", "w szczycie"), ("Użytkownicy", "4", 0, "osoby", "2 sypialnie, 2 łazienki"), ("Kondygnacje", "2", 0, "", "parter + poddasze z tarasem")],
        interiors=[("forest/int-7.webp", False), ("forest/int-1.webp", False), ("forest/int-3.webp", True), ("forest/int-10.webp", False), ("forest/int-4.webp", True), ("forest/int-11.webp", False), ("forest/int-5.webp", True), ("forest/int-8.webp", True), ("forest/int-6.webp", True), ("forest/int-9.webp", True)],
        variants=[("Dom całoroczny", "Prywatny dom na działce: izolowane przegrody, ogrzewanie i pełne wykończenie wnętrza.", "zastosowanie", "../img/forest/ext-2.webp", "Dom całoroczny"),
                  ("Inwestycja pod wynajem", "Produkt gotowy do wykorzystania: układ dla 4 osób, dwie łazienki, taras.", "zastosowanie", "../img/forest/ext-3.webp", "Wynajem krótkoterminowy"),
                  ("Resort lub glamping", "Zespół kilku domów na działce rekreacyjnej lub w resorcie: powtarzalny moduł, krótki montaż.", "zastosowanie", "../img/forest/glamping.webp", "Zespół domów"),
                  ("Indywidualny standard", "Zakres wykończenia dopasowujemy do inwestycji prywatnej, rekreacyjnej lub komercyjnej.", "konfiguracja", None, "Konfiguracja")],
        plans=[("forest/plan-parter.webp", "Rzut parteru", "salon, kuchnia, łazienka, sypialnia"), ("forest/plan-pietro.webp", "Rzut drugiej kondygnacji", "sypialnia, łazienka, taras"), ("forest/elev-1.webp", "Elewacja boczna", ""), ("forest/elev-2.webp", "Elewacja frontowa", "")],
        spec=SPEC_FOREST, standard=STD_FOREST, next="archouse-70"),
]
BY_SLUG = {p["slug"]: p for p in PROJECTS}
AREA_MAX = 130
def title_of(p): return f"{p['name']} {p['num']}".strip()
